[project]
name = "sql-kertaus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "skimpy>=0.0.18",
    "sqlalchemy>=2.0.44",
]
